name: Feature Request
description: Suggest a new feature
type: "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature and its use case
    validations:
      required: true
  - type: checkboxes
    id: maplibre_support
    attributes:
      label: MapLibre Support
      description: Which MapLibre SDKs support this feature?
      options:
        - label: MapLibre Native for Android
        - label: MapLibre Native for iOS
        - label: MapLibre GL JS
  - type: textarea
    id: maplibre_docs
    attributes:
      label: MapLibre Documentation Links
      description: Please provide links to relevant MapLibre documentation.
      placeholder: |
        - Android: https://maplibre.org/maplibre-native/android/api/...
        - iOS: https://maplibre.org/maplibre-native/ios/latest/documentation/maplibre/...
        - JS: https://maplibre.org/maplibre-gl-js/docs/...
  - type: dropdown
    id: willing_to_pr
    attributes:
      label: Implementation
      description: Would you be willing to implement this feature and submit a PR?
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: development_platforms
    attributes:
      label: Development Platforms
      description: If you're willing to implement this, which platforms can you develop for?
      options:
        - label: Android
        - label: iOS
        - label: Browser
        - label: Linux (x86_64)
        - label: Linux (aarch64)
        - label: macOS (x86_64)
        - label: macOS (aarch64)
        - label: Windows (x86_64)
        - label: Windows (aarch64)
